In [51]:
import cv2
import numpy

In [18]:
im_grey=cv2.imread("smallgray.png",0) #read image to numpy object with cv2 lib method .imread (image read) , argument 0 = as gray scale, 1 = as RGB

In [20]:
type(im_grey)

numpy.ndarray

In [21]:
im_grey   # in gray scale you get 2 dimensional array of picture, one value for each pixel

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [27]:
im_bgr=cv2.imread("smallgray.png",1) #read image to numpy object with cv2 lib method .imread (image read) , argument 0 = as gray scale, 1 = as BGR

In [28]:
im_bgr #3 dimensional array, first is values for BLUE, second for GREEN, third for RED

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [29]:
cv2.imwrite("newpic.png",im_bgr) #create new pictutre file from numpy array with cv2.inwrite

True

In [35]:
im_grey=cv2.imread("smallgray.png",0) #read image to numpy object with cv2 lib method .imread (image read) , argument 0 = as gray scale, 1 = as RGB

In [36]:
im_grey

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [39]:
im_grey[0:2, 2:4] #slicing array [rows, columns]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [45]:
for i in im_grey:    #iterating through array in lines
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [48]:
for i in im_grey.T:     #iterating through array in columns
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [49]:
for i in im_grey.flat:      #iterationg through array one by one
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [58]:
ims=numpy.hstack(im_grey,im_grey) #horisontal stacking on arrays, .hstack takes only one positional argument so two arrays are given inside ()

TypeError: hstack() takes 1 positional argument but 2 were given

In [59]:
ims=numpy.hstack((im_grey,im_grey)) #horisontal stacking on arrays, .hstack takes only one input so two arrays are given inside ()

In [60]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [67]:
vims=numpy.vstack((ims,ims)) #vertical stacking of arrays
print(vims) 

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]
 [187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [68]:
vims=numpy.vstack((ims,ims[:,0:3])) #second array has different number on columns, see error

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [72]:
lst=numpy.vsplit(vims,3) #spliting arrays makes list of numpy arrays. argument 3 is how many. you can acces individual list normally by lst[0] for first and so on
type(lst)

list

In [73]:
lst

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]

In [74]:
lst2=numpy.vsplit(vims,4) #when splitting resulting arrays needs to be same size, here tried to split 6 row array into 4 and gives an error

ValueError: array split does not result in an equal division